VIA_ENABLE = yes
VIAL_ENABLE = yes

QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes

VIALRGB_ENABLE = yes
RGB_MATRIX_ENABLE = yes

LTO_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
